version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: bso-dev-image
    container_name: bso-blog-develop
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./app-develop:/app
      - /develop_app/node_modules
    networks:
      - develop-network
    restart: unless-stopped
    
networks:
  develop-network:
    driver: bridge
