services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: bso-prod-image
    container_name: bso-blog-production
    environment:
      NODE_ENV: production
    ports:
      - "9009:3000"
    env_file:
      - .env
    networks:
      - production-network
      - centralized-postgresql_db-network
    restart: unless-stopped

networks:
  production-network:
    driver: bridge
  centralized-postgresql_db-network:
    external: true